apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cgp88o0tu-nodejs
  janus-idp.io/tekton: cgp88o0tu-nodejs
  backstage.io/kubernetes-id: cgp88o0tu-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cgp88o0tu-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
