apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cgp88o0tu-nodejs 
  janus-idp.io/tekton: cgp88o0tu-nodejs
  backstage.io/kubernetes-id: cgp88o0tu-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cgp88o0tu-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml